# Generated by Django 5.1.5 on 2025-02-11 07:16

import database.models.photo
import database.models.profile
import database.models.session
import django.db.models.deletion
import django.utils.timezone
import helpers.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('bio', models.TextField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('avatar', models.FileField(null=True, upload_to=database.models.profile.upload_avatar)),
            ],
            options={
                'db_table': 'auth_user_profile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_code', models.CharField(db_index=True, default=database.models.session.create_session_code, max_length=25)),
                ('session_name', models.CharField(default=database.models.session.create_session_name, max_length=50)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=15, null=True, unique=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='database.profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('file', models.FileField(upload_to=database.models.photo.upload_photo)),
                ('filename', models.CharField(max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='database.session')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(default=helpers.utils.generate_oid, max_length=21)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='database.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_users',
            },
        ),
    ]
