"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from importlib.util import find_spec
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

PROJECT_NAME = config('PROJECT_NAME', default="Django REST Framework API", cast=str)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(",")])

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=lambda v: [s.strip() for s in v.split(",")])

SECURE_SSL_REDIRECT = config('ENABLE_HTTPS', default=False, cast=bool)

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "django_filters",
    "rest_framework",
    "drf_standardized_errors",

    "api",
    "core",
    "database",
    "middlewares",
    "tasks",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Append URL Slash
# https://docs.djangoproject.com/en/5.1/ref/settings/#append-slash

APPEND_SLASH = True


# Django REST Framework
# https://www.django-rest-framework.org/tutorial/quickstart/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ["rest_framework.authentication.BasicAuthentication"],
    'DEFAULT_PERMISSION_CLASSES': ["rest_framework.permissions.AllowAny"],
    'DEFAULT_RENDERER_CLASSES': ["helpers.response.ResponseRenderer"],
    'EXCEPTION_HANDLER': "drf_standardized_errors.handler.exception_handler",
    'DEFAULT_VERSIONING_CLASS': "core.api_versioning.APIVersioning",
    'DEFAULT_VERSION': "v1",
}


# DRF Standardized Errors
# https://drf-standardized-errors.readthedocs.io/en/latest/settings.html

DRF_STANDARDIZED_ERRORS = {
    'EXCEPTION_FORMATTER_CLASS': "helpers.exception.StandardExceptionFormatter",
}


# Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-broker_url

CELERY_TIMEZONE = config('DJANGO_TIMEZONE', default="Asia/Jakarta", cast=str)

CELERY_BROKER_URL = config('REDIS_URL', default="redis://localhost:6379/0")

CELERY_CACHE_BACKEND = "django-cache"

CELERY_RESULT_BACKEND = "django-db"

CELERY_RESULT_EXTENDED = True


# Cache
# https://docs.djangoproject.com/en/5.1/topics/cache/

CACHES = {
    'default': {
        'BACKEND': "django_redis.cache.RedisCache",
        'LOCATION': config('REDIS_URL', default="redis://localhost:6379/0"),
        'TIMEOUT': 300,
        'OPTIONS': {
            'CLIENT_CLASS': "django_redis.client.DefaultClient",
            'PARSER_CLASS': "redis.connection._HiredisParser",
            'COMPRESSOR': "django_redis.compressors.lz4.Lz4Compressor",
        },
        'KEY_PREFIX': PROJECT_NAME,
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

AUTH_USER_MODEL = "database.User"

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.postgresql",
        'NAME': config('DB_NAME', default="postgres", cast=str),
        'USER': config('DB_USER', default="postgres", cast=str),
        'PASSWORD': config('DB_PASS', default="postgres", cast=str),
        'HOST': config('DB_HOST', default="localhost", cast=str),
        'PORT': config('DB_PORT', default=5432, cast=int),
    }
}


# Storage
# https://docs.djangoproject.com/en/5.1/ref/files/storage/

STORAGES = {
    'default': {
        'BACKEND': "storages.backends.s3.S3Storage",
        'OPTIONS': {
            'access_key': config('AWS_S3_ACCESS_KEY', default="", cast=str),
            'secret_key': config('AWS_S3_SECRET_KEY', default="", cast=str),
            'bucket_name': config('AWS_S3_BUCKET_NAME', default="", cast=str),
            'endpoint_url': config('AWS_S3_ENDPOINT_URL', default="", cast=str),
        }
    },
    'staticfiles': {
        'BACKEND': "django.core.files.storage.FileSystemStorage"
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / "static"
    ]
else:
    STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "uploads"


# Session
# https://docs.djangoproject.com/en/5.1/topics/http/sessions/

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

SESSION_CACHE_ALIAS = "default"

SESSION_COOKIE_AGE = 604800


# Authentication and authorization
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "core.authentication.AuthenticationBackend",
]

OTP_AUTH = config('OTP_AUTH', default=False, cast=bool)

OTP_MAX_RETRIES = 3

JWT_ALGORITHM = "HS256"

JWT_EXP_HOURS = 2


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {'NAME': "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {'NAME': "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {'NAME': "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = [ "django.contrib.auth.hashers.ScryptPasswordHasher" ]


# Mailing
# https://docs.djangoproject.com/en/5.1/topics/email/

EMAIL_BACKEND = config('DJANGO_EMAIL_BACKEND', default="django.core.mail.backends.console.EmailBackend", cast=str)

EMAIL_HOST = config('DJANGO_EMAIL_HOST', default="localhost", cast=str)

EMAIL_PORT = config('DJANGO_EMAIL_PORT', default=25, cast=int)

EMAIL_HOST_USER = config('DJANGO_EMAIL_HOST_USER', default="", cast=str)

EMAIL_HOST_PASSWORD = config('DJANGO_EMAIL_HOST_PASSWORD', default="", cast=str)

EMAIL_USE_TLS = config('DJANGO_EMAIL_USE_TLS', default=False, cast=bool)

EMAIL_USE_SSL = config('DJANGO_EMAIL_USE_SSL', default=False, cast=bool)

DEFAULT_FROM_EMAIL = config('DJANGO_DEFAULT_FROM_EMAIL', default="no-reply@localhost", cast=str)


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = config('DJANGO_LANGCODE', default="en-us", cast=str)

TIME_ZONE = config('DJANGO_TIMEZONE', default="Asia/Jakarta", cast=str)

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/

FILE_HANDLER = "logging.FileHandler"

if find_spec('rich'):
    CONSOLE_LOGGER_CLASS = "rich.logging.RichHandler"
else:
    CONSOLE_LOGGER_CLASS = "logging.StreamHandler"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "{levelname} {asctime} {module} {message}",
            'style': "{",
        },
        'simple': {
            'format': "{message}",
            'style': "{",
        },
    },
    'handlers': {
        'console': {
            'level': "INFO",
            'class': CONSOLE_LOGGER_CLASS,
            'formatter': "simple",
        },
        'file': {
            'level': "WARNING",
            'class': FILE_HANDLER,
            'filename': BASE_DIR / "logs" / "django.log",
            'formatter': "verbose",
        },
        'celery_beat': {
            'level': "INFO",
            'class': FILE_HANDLER,
            'filename': BASE_DIR / "logs" / "celery_beat.log",
            'formatter': "verbose",
        },
        'celery_worker': {
            'level': "INFO",
            'class': FILE_HANDLER,
            'filename': BASE_DIR / "logs" / "celery_worker.log",
            'formatter': "verbose",
        },
    },
    'root': {
        'handlers': ["console"],
        'level': "DEBUG",
    },
    'loggers': {
        'django': {
            'handlers': ["file"],
            'level': "INFO",
            'propagate': True,
        },
        'celery': {
            'handlers': ["celery_worker"],
            'level': "INFO",
            'propagate': True,
        },
        'django_celery_beat': {
            'handlers': ["celery_beat"],
            'level': "INFO",
            'propagate': True,
        }
    },
}


# Testing
# https://docs.djangoproject.com/en/5.1/topics/testing/

TEST_RUNNER = "tests.test_runner.TestRunner"


# Sentry
# https://docs.sentry.io/platforms/python/configuration/options/

SENTRY_DSN = config('SENTRY_DSN', default=None, cast=str)

if not DEBUG and SENTRY_DSN:
    from sentry_sdk import init
    init(dsn=f"{SENTRY_DSN}", traces_sample_rate=1.0, profiles_sample_rate=1.0)
